### ISSUE TITLE
Custo do produto por horas de trabalho

### ISSUE THREAD

**Issue by Linque2** [nadas-t/Projeto_MC656#2]
O usuário deve ser capaz de visualizar seus gastos, passados ou futuros, na forma das suas horas trabalhadas. Essa funcionalidade traz uma maneira compreensível de mensurar os esforços relacionados a uma despesa, levando o usuário a refletir sobre suas finanças, e evitar gastos impulsivos.

**Comment by nadas-t** [comment]
xa comigo essa

**Comment by IsacL21** [comment]
Feature implementada no commit 5cac2fc.

**Comment by IsacL21** [comment]
Testes unitários implementados no commit 5a1e8b4.

**Comment by IsacL21** [comment]
Issue finalizado com o merge do commit 4fdff51.
