### ISSUE TITLE
Smell: Long method

### ISSUE THREAD

**Issue by Linque2** [nadas-t/Projeto_MC656#28]
https://github.com/nadas-t/Projeto_MC656/blob/9e3a615fb6538f7c1a83bbb3148ad0a26c0a3923/app/Model/gastosModel.py#L6-L32

Em uma mesma função, a lógica responsável por cadastrar gastos no banco de dados precisa:
1. Iniciar a comunicação com o banco;
2. Verificar se a categoria do gasto inserido existe;
3. Realiza a operação de criação ou recuperação da categoria baseada na resposta do último item;
5. Realiza o tratamento de exceção caso a operação do banco falhe;
6. Registra o gasto no banco de forma persistente;
7.  E por fim encerra a conexão com o banco;

**Problema**: Como todas as operações são implementadas diretamente no código, sem chamadas de funções externas, o código da implementação se torna extenso, dificultando a leitura (questão mascarada pelo uso de comentários), e reduzindo a reusabilidade do código.

**Tratamento**: Um possível tratamento seria realizar a operação de "[Extract Method](https://refactoring.guru/replace-method-with-method-object)" que envolve reescrever partes da função original como métodos a separados, responsáveis por operações pequenas, além de reduzir a quantidade de linhas da função, a abordagem permite nomear cada nova função com nomes mais significativos, o que implica em uma melhora significativa na legibilidade do código. Além disso, cada novo método pode ser reutilizado em outras porções do código caso se faça necessário.

**Comment by brenofranca83** [comment]
Parabéns pelos snippets na issue, vou tornar isso padrão nas entregas! Facilita muito!
